[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-oodwaita
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-oodwaita
GtkTheme=oomox-oodwaita
IconTheme=oomox-oodwaita
MetacityTheme=oomox-oodwaita
