[pyprland]
plugins = [ "scratchpads" ]

[scratchpads.term]
command = "kitty --override background=#e9e9e9 --class kitty-scratch"
animation = "fromBottom"
margin = 50
unfocus = "hide"
lazy = true
size = "50% 30%"
max_size = "1920px 100%"

