[pyprland]
plugins = [ "scratchpads" ]

[scratchpads.term]
command = "kitty --override background=#1e1e24 --override background_opacity=0.75 --class kitty-scratch"
class = "kitty-scratch"
animation = "fromBottom"
margin = 50
unfocus = "hide"
lazy = false
size = "50% 30%"
max_size = "1920px 100%"

