[default]
# path = "/usr/share/backgrounds/Sunset.png"
# path = "/usr/share/backgrounds/Take a Pipebomb (Background).jpg"
path = "/usr/share/backgrounds/Paint Explosion Profile.png"
# path = "/usr/share/backgrounds/Rain in Berlin.png"
apply-shadow = true
