theme = "custom"

[editor]
line-number = "relative"
idle-timeout = 100
scroll-lines = 1
completion-trigger-len = 1
completion-timeout = 5
# completion-replace = true
shell = ["fish", "-c"]
popup-border = "none"
# mouse = false
end-of-line-diagnostics = "info"

[editor.lsp]
display-messages = false
auto-signature-help = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spacer", "diagnostics", "file-base-name", "file-modification-indicator"]
center = []
right = ["version-control", "spacer", "file-type", "position"]
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

# [editor.lsp]
# display-inlay-hints = true

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "info"
other-lines = "info"
