[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs"]
roots = ["sln", "csproj"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }

[language-server.c-sharp]
command = "omnisharp"
args = [ "--languageserver" ]

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "haskell"
indent = { tab-width = 4, unit = "  " }
